[tool.poetry]
name = "ns-generator"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
PyYAML = "^6.0.1"
numpy = "^2.0.0"
soundfile = "^0.12.1"
loguru = "^0.7.2"
requests = "^2.32.3"

[tool.poetry.group.server.dependencies]
gradio-client = "^1.0.2"
fastapi = "^0.111.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
